 version: 2.1

 orbs:
   slack: circleci/slack@1.0.0

 jobs:
   build:
     docker:
       - image: circleci/node:10.16.3
     steps:
       - checkout
       - run: echo "A first hello"
       - slack/notify:
           message: "Test"
